host: "tun.example.com"
wireGuard:
  network: "10.69.0.0/16"
  port: "4444"
  interfaceName: "tunnel"
expireAfter: 86400
#tls:
#  enabled: true
#  cert: "/etc/ssl/certs/tun.example.com.crt"
#  key: "/etc/ssl/private/tun.example.com.key"